create table Carros (
  Id int generated by default as identity not null,
  Nome varchar(300) not null,
  Eixos int not null,
  Categoria varchar(100) not null,
  TamanhoPortaMalas int not null,
  Portas int not null,
  Preco decimal not null,
  CreatedAt timestamp not null,
  UpdatedAt timestamp not null,
  constraint Carros_pk
    primary key (Id)
);
insert into "teste-web-fullstack".dbo.Carros (
  Id,
  Nome,
  Eixos,
  Categoria,
  TamanhoPortaMalas,
  Portas,
  Preco,
  CreatedAt,
  UpdatedAt
)
values (
  2,
  'New Fiesta',
  2,
  'Hatch',
  250,
  4,
  40000,
  '2021-08-19 16:19:03.000',
  '2021-08-19 16:19:05.000'
);
insert into "teste-web-fullstack".dbo.Carros (
  Id,
  Nome,
  Eixos,
  Categoria,
  TamanhoPortaMalas,
  Portas,
  Preco,
  CreatedAt,
  UpdatedAt
)
values (
  3,
  'Civic',
  2,
  'Sedan',
  400,
  4,
  85707,
  '2021-08-19 16:22:35.000',
  '2021-08-19 16:22:39.000'
);